server:
  port: 9000

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  jackson:
    default-property-inclusion: non_null
kafka-topic:
  input-topic: test_topic
  output-topic: test_ouput

